### ISSUE TITLE
Project Roadmap 08/2016

### ISSUE THREAD

**Issue by marcossffilho** [marcossffilho/task-progress#1]
Features to be released in v1.0.0
----------------------------------------------------

 * [ ] Task Progress API
   - [X] Default progress (8889f83)
   - [X] Line-by-line progress (30ec8fc)
   - [X] Update task list (7cd641f)
   - [ ] Informational messages
 * [ ] Task Executor API
   - [ ] Promise executor
   - [ ] Generator executor
   - [ ] Iterator executor
